pipeline {
    agent any
    
    triggers{
        cron('0 3 * * 1-5')
    }

    stages {
        stage('SCM'){
            steps {
          	   git branch: 'main', credentialsId: '1112', url: 'git@github.com:ZhivkoTringov/declarative-pipelines.git'
            }
        }
        stage('build') {
            steps{
                echo "build the code"
            }
            
        }
    }
}
