pipeline {
    agent any
    
    parameters{
        string(name: 'branch', defaultValue: 'main', description: 'The branch to fetch for the pipeline')
    }

    triggers{
        cron('0 3 * * 1-5')
    }

    stages {
        stage('SCM'){
            steps {
          	   git branch: 'main', credentialsId: '1112', url: 'git@github.com:ZhivkoTringov/declarative-pipelines.git'
            }
        }
        stage('build') {
            steps{
                echo "build the code"
            }
            
        }
        stage('Package') {
            when {
                expression {
                    return params.branch == "release"
                }
            }
            steps {
                echo 'Packaging the code release'
            }
        }
    }
}
