pipeline {
    agent any
    
    triggers{
        cron('0 3 * * 1-5')
    }

    stages {
        stage('build') {
            steps{
                echo "build the code"
            }
            
        }
        stage('Package') {
            when {
                expression {
                    return params.branch == "release"
                }
            }
            steps {
                echo 'Packaging the code release'
            }
        }
        stage('Buld is Successful'){
            steps {
                echo 'Test to Discord'
                discordSend customAvatarUrl: '', customFile: '', customUsername: '', description: 'Build Completed', footer: '', image: '', link: '', result: currentBuild.currentResult, scmWebUrl: '', thumbnail: '', title: 'Build Notification', webhookURL: 'https://discord.com/api/webhooks/1353681555716964432/Bd-e5dQbBGBnAT1syqvdxUjgju6B2OwZBQ7nsWrOgabr04wlwjhPzTWI2M2qzwOKXnMP'
            }
        }
    }
}
